resource_types:
- name: git-head
  type: docker-image
  source:
    repository: jtarchie/git-head-resource
    branches:
      only: /pr/

resources:
- name: github-pullrequest-resource
  type: git-head
  source:
    uri: https://github.com/jtarchie/github-pullrequest-resource

jobs:
- name: example
  plan:
  - get: github-pullrequest-resource
    trigger: true
    version: every
